// Events
export const SET_EVENTS = "SET_EVENTS";

// NonApprovedEvents
export const GET_NON_APPROVED_EVENTS = "GET_NON_APPROVED_EVENTS";
export const GET_NON_APPROVED_EVENTS_COUNT = "GET_NON_APPROVED_EVENTS_COUNT";
export const APPROVE_EVENT = "APPROVE_EVENT";

export const SET_NON_APPROVED_EVENTS = "SET_NON_APPROVED_EVENTS";
export const SET_NON_APPROVED_EVENTS_COUNT = "SET_NON_APPROVED_EVENTS_COUNT";

// Fields

// FieldSizes
export const SET_AVAILABLE_FIELD_SIZES = "SET_AVAILABLE_FIELD_SIZES";

// Login
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SET_IS_SIGNED_IN = "SET_IS_SIGNED_IN";
export const SET_USER_KEY = "";

// Changingrooms
export const FETCH_CHANGINGROOMS = "FETCH_CHANGINGROOMS";
export const FETCH_AVAILABLE_CHANGINGROOMS = "FETCH_AVAILABLE_CHANGINGROOMS";

export const SET_CHANGINGROOMS = "SET_CHANGINGROOMS";
export const SET_AVAILABLE_CHANGINGROOMS = "SET_AVAILABLE_CHANGINGROOMS";

// Modals
export const SET_ALTER_EVENT_MODAL_IS_HIDDEN = "SET_ALTER_EVENT_MODAL_IS_HIDDEN";
export const SET_APPROVE_EVENT_MODAL_IS_HIDDEN = "SET_APPROVE_EVENT_MODAL_IS_HIDDEN";
export const SET_LOGIN_MODAL_IS_HIDDEN = "SET_LOGIN_MODAL_IS_HIDDEN";
export const SET_NEW_EVENT_MODAL_IS_HIDDEN = "SET_NEW_EVENT_MODAL_IS_HIDDEN";

// Admins
export const SET_IS_ADMIN = "SET_IS_ADMIN";

// Dates
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

// Menu
export const SET_IS_MENU_OPEN = "SET_IS_MENU_OPEN";

// Api
export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const API_ERROR = "API_ERROR";
export const API_DENIED = "API_DENIED";

// SessionStorage
export const SESSION_STORAGE_SET_ITEM = "SESSION_STORAGE_SET_ITEM";