// Events
export const GET_EVENTS = "GET_EVENTS";
export const POST_EVENT = "POST_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const SET_EVENTS = "SET_EVENTS";

// NonApprovedEvents
export const GET_NON_APPROVED_EVENTS = "GET_NON_APPROVED_EVENTS";
export const GET_NON_APPROVED_EVENTS_COUNT = "GET_NON_APPROVED_EVENTS_COUNT";
export const APPROVE_EVENT = "APPROVE_EVENT";

export const SET_NON_APPROVED_EVENTS = "SET_NON_APPROVED_EVENTS";
export const SET_NON_APPROVED_EVENTS_COUNT = "SET_NON_APPROVED_EVENTS_COUNT";

// Fields
export const GET_FIELD_SIZES = "GET_FIELD_SIZES";

export const SET_FIELD_SIZES = "SET_FIELD_SIZES";

// Login
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SET_IS_SIGNED_IN = "SET_IS_SIGNED_IN";

// Changingrooms
export const GET_ALL_CHANGINGROOMS = "GET_ALL_CHANGINGROOMS";
export const GET_CHANGINGROOMS_INBETWEEN = "GET_CHANGINGROOMS_INBETWEEN";

export const SET_CHANGINGROOMS = "SET_CHANGINGROOMS";

// Api
export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const API_ERROR = "API_ERROR";
export const API_DENIED = "API_DENIED";

// Modals
export const SET_ALTER_EVENT_MODAL_IS_HIDDEN = "SET_ALTER_EVENT_MODAL_IS_HIDDEN";
export const SET_APPROVE_EVENT_MODAL_IS_HIDDEN = "SET_APPROVE_EVENT_MODAL_IS_HIDDEN";
export const SET_LOGIN_MODAL_IS_HIDDEN = "SET_LOGIN_MODAL_IS_HIDDEN";
export const SET_NEW_EVENT_MODAL_IS_HIDDEN = "SET_NEW_EVENT_MODAL_IS_HIDDEN";